/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_api_v1_clients_get"];
        put?: never;
        /** Create Client */
        post: operations["create_client_api_v1_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Client */
        put: operations["update_client_api_v1_clients__client_id__put"];
        post?: never;
        /** Delete Client */
        delete: operations["delete_client_api_v1_clients__client_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client Folders */
        get: operations["get_client_folders_api_v1_clients__client_id__folders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Client File */
        get: operations["download_client_file_api_v1_clients__client_id__files__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload-invoice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Invoice */
        post: operations["upload_invoice_api_v1_upload_invoice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload-invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Invoices Batch */
        post: operations["upload_invoices_batch_api_v1_upload_invoices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Invoices */
        get: operations["list_invoices_api_v1_invoices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Invoice */
        get: operations["get_invoice_api_v1_invoices__invoice_id__get"];
        put?: never;
        post?: never;
        /** Delete Invoice */
        delete: operations["delete_invoice_api_v1_invoices__invoice_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{invoice_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Review Invoice */
        put: operations["review_invoice_api_v1_invoices__invoice_id__review_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{invoice_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Approve Invoice */
        put: operations["approve_invoice_api_v1_invoices__invoice_id__approve_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bank-statements/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Bank */
        post: operations["upload_bank_api_v1_bank_statements_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bank-statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bank */
        get: operations["list_bank_api_v1_bank_statements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bank-statements/{bank_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Bank Statement */
        delete: operations["delete_bank_statement_api_v1_bank_statements__bank_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reconciliations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reconciliations */
        get: operations["list_reconciliations_api_v1_reconciliations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reconciliations/{recon_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Reconciliation
         * @description Undo a match: remove the reconciliation row and reopen the bank row
         *     (bank row itself is kept).
         */
        delete: operations["delete_reconciliation_api_v1_reconciliations__recon_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Reconcile */
        post: operations["run_reconcile_api_v1_reconcile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export-tally": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Tally */
        get: operations["export_tally_api_v1_export_tally_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{invoice_id}/duplicates/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Duplicates */
        post: operations["check_duplicates_api_v1_invoices__invoice_id__duplicates_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/duplicates/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Flags */
        get: operations["list_flags_api_v1_duplicates_flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/duplicates/flags/{flag_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Flag */
        post: operations["resolve_flag_api_v1_duplicates_flags__flag_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reminder Preview */
        get: operations["reminder_preview_api_v1_reminders_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}/send-reminder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Client Reminder */
        post: operations["send_client_reminder_api_v1_clients__client_id__send_reminder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reminder History */
        get: operations["reminder_history_api_v1_reminders_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/{reminder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Reminder */
        delete: operations["delete_reminder_api_v1_reminders__reminder_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_api_v1_reminders_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BankStatementOut */
        BankStatementOut: {
            /** Client Id */
            client_id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Narration */
            narration: string;
            /**
             * Debit
             * @default 0
             */
            debit: number;
            /**
             * Credit
             * @default 0
             */
            credit: number;
            /** Balance */
            balance?: number | null;
            /** Id */
            id: number;
            /** Reconciled */
            reconciled: boolean;
            /** Invoice Id */
            invoice_id?: number | null;
            /** File Path */
            file_path?: string | null;
        };
        /** Body_upload_bank_api_v1_bank_statements_upload_post */
        Body_upload_bank_api_v1_bank_statements_upload_post: {
            /** File */
            file: string;
        };
        /** Body_upload_invoice_api_v1_upload_invoice_post */
        Body_upload_invoice_api_v1_upload_invoice_post: {
            /** File */
            file: string;
            /** Client Id */
            client_id?: number | null;
            /**
             * Invoice Type
             * @default sales
             */
            invoice_type: string;
        };
        /** Body_upload_invoices_batch_api_v1_upload_invoices_post */
        Body_upload_invoices_batch_api_v1_upload_invoices_post: {
            /** Files */
            files: string[];
            /** Client Id */
            client_id: number;
            /**
             * Invoice Type
             * @default sales
             */
            invoice_type: string;
        };
        /** ClientCreate */
        ClientCreate: {
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
            /** Gst Number */
            gst_number?: string | null;
            /** Address */
            address?: string | null;
        };
        /** ClientOut */
        ClientOut: {
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
            /** Gst Number */
            gst_number?: string | null;
            /** Address */
            address?: string | null;
            /** Id */
            id: number;
            /**
             * Auto Created
             * @default false
             */
            auto_created: boolean;
        };
        /** ClientUpdate */
        ClientUpdate: {
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Gst Number */
            gst_number?: string | null;
            /** Address */
            address?: string | null;
        };
        /** DuplicateFlagOut */
        DuplicateFlagOut: {
            /** Invoice Id */
            invoice_id: number;
            /** Potential Duplicate Id */
            potential_duplicate_id: number;
            /** Similarity Score */
            similarity_score: number;
            /** Matched Fields */
            matched_fields?: string | null;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Id */
            id: number;
            /** Created At */
            created_at?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
        };
        /** DuplicateResolve */
        DuplicateResolve: {
            /** Action */
            action: string;
        };
        /** DuplicateScanResult */
        DuplicateScanResult: {
            /** Invoice Id */
            invoice_id: number;
            /** Flags Created */
            flags_created: number;
            /**
             * Matches
             * @default []
             */
            matches: components["schemas"]["DuplicateFlagOut"][];
        };
        /** EmailReminderOut */
        EmailReminderOut: {
            /** Id */
            id: number;
            /** Client Id */
            client_id: number;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            /** Status */
            status: string;
            /** Error Message */
            error_message?: string | null;
            /** Sent At */
            sent_at?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvoiceCreate */
        InvoiceCreate: {
            /** Client Id */
            client_id: number;
            /** Invoice Number */
            invoice_number?: string | null;
            /** Invoice Date */
            invoice_date?: string | null;
            /** Company Name */
            company_name?: string | null;
            /**
             * Gst Rate
             * @default 0
             */
            gst_rate: number;
            /**
             * Taxable Value
             * @default 0
             */
            taxable_value: number;
            /**
             * Total Amount
             * @default 0
             */
            total_amount: number;
            /**
             * Cgst
             * @default 0
             */
            cgst: number;
            /**
             * Sgst
             * @default 0
             */
            sgst: number;
            /**
             * Igst
             * @default 0
             */
            igst: number;
            /** Hsn Code */
            hsn_code?: string | null;
            /** Quantity */
            quantity?: number | null;
            /** Item Description */
            item_description?: string | null;
            /**
             * Invoice Type
             * @default sales
             */
            invoice_type: string;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["InvoiceItemCreate"][] | null;
        };
        /** InvoiceItemCreate */
        InvoiceItemCreate: {
            /** Description */
            description: string;
            /** Hsn Code */
            hsn_code?: string | null;
            /** Quantity */
            quantity: number;
            /** Rate */
            rate: number;
            /** Taxable Value */
            taxable_value: number;
            /**
             * Gst Rate
             * @default 0
             */
            gst_rate: number;
            /**
             * Cgst
             * @default 0
             */
            cgst: number;
            /**
             * Sgst
             * @default 0
             */
            sgst: number;
            /**
             * Igst
             * @default 0
             */
            igst: number;
            /** Line Total */
            line_total: number;
        };
        /** InvoiceItemOut */
        InvoiceItemOut: {
            /** Description */
            description: string;
            /** Hsn Code */
            hsn_code?: string | null;
            /** Quantity */
            quantity: number;
            /** Rate */
            rate: number;
            /** Taxable Value */
            taxable_value: number;
            /**
             * Gst Rate
             * @default 0
             */
            gst_rate: number;
            /**
             * Cgst
             * @default 0
             */
            cgst: number;
            /**
             * Sgst
             * @default 0
             */
            sgst: number;
            /**
             * Igst
             * @default 0
             */
            igst: number;
            /** Line Total */
            line_total: number;
            /** Id */
            id: number;
        };
        /** InvoiceOut */
        InvoiceOut: {
            /** Client Id */
            client_id: number;
            /** Invoice Number */
            invoice_number?: string | null;
            /** Invoice Date */
            invoice_date?: string | null;
            /** Company Name */
            company_name?: string | null;
            /**
             * Gst Rate
             * @default 0
             */
            gst_rate: number;
            /**
             * Taxable Value
             * @default 0
             */
            taxable_value: number;
            /**
             * Total Amount
             * @default 0
             */
            total_amount: number;
            /**
             * Cgst
             * @default 0
             */
            cgst: number;
            /**
             * Sgst
             * @default 0
             */
            sgst: number;
            /**
             * Igst
             * @default 0
             */
            igst: number;
            /** Hsn Code */
            hsn_code?: string | null;
            /** Quantity */
            quantity?: number | null;
            /** Item Description */
            item_description?: string | null;
            /**
             * Invoice Type
             * @default sales
             */
            invoice_type: string;
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Approved */
            approved: boolean;
            /** Ocr Confidence */
            ocr_confidence?: number | null;
            /** File Path */
            file_path?: string | null;
            /**
             * Is Duplicate
             * @default false
             */
            is_duplicate: boolean;
            /** Duplicate Of */
            duplicate_of?: number | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["InvoiceItemOut"][];
            /** Audit */
            audit?: {
                [key: string]: unknown;
            } | null;
        };
        /** ReconciliationOut */
        ReconciliationOut: {
            /** Id */
            id: number;
            /** Invoice Id */
            invoice_id: number;
            /** Invoice Number */
            invoice_number?: string | null;
            /** Bank Statement Id */
            bank_statement_id: number;
            /** Narration */
            narration?: string | null;
            /** Amount */
            amount?: number | null;
            /** Match Score */
            match_score: number;
            /** Matched By */
            matched_by?: string | null;
            /** Confirmed */
            confirmed: boolean;
            /** Created At */
            created_at?: string | null;
        };
        /** ReminderSend */
        ReminderSend: {
            /** Template Name */
            template_name?: string | null;
            /** Custom Message */
            custom_message?: string | null;
            /**
             * Days
             * @default 30
             */
            days: number | null;
            /**
             * Send
             * @default true
             */
            send: boolean;
        };
        /** ReminderTemplate */
        ReminderTemplate: {
            /** Name */
            name: string;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
        };
        /** UploadFileResult */
        UploadFileResult: {
            /** Filename */
            filename: string;
            /** Status */
            status: string;
            invoice?: components["schemas"]["InvoiceOut"] | null;
            /** Error */
            error?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_clients_api_v1_clients_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_api_v1_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_client_api_v1_clients__client_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_client_api_v1_clients__client_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_folders_api_v1_clients__client_id__folders_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_client_file_api_v1_clients__client_id__files__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_invoice_api_v1_upload_invoice_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_invoice_api_v1_upload_invoice_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_invoices_batch_api_v1_upload_invoices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_invoices_batch_api_v1_upload_invoices_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadFileResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invoices_api_v1_invoices_get: {
        parameters: {
            query?: {
                client_id?: number | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_invoice_api_v1_invoices__invoice_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_invoice_api_v1_invoices__invoice_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_invoice_api_v1_invoices__invoice_id__review_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_invoice_api_v1_invoices__invoice_id__approve_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_bank_api_v1_bank_statements_upload_post: {
        parameters: {
            query: {
                client_id: number;
                preview?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_bank_api_v1_bank_statements_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bank_api_v1_bank_statements_get: {
        parameters: {
            query?: {
                client_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankStatementOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_bank_statement_api_v1_bank_statements__bank_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bank_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reconciliations_api_v1_reconciliations_get: {
        parameters: {
            query?: {
                client_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_reconciliation_api_v1_reconciliations__recon_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recon_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_reconcile_api_v1_reconcile_post: {
        parameters: {
            query: {
                client_id: number;
                min_score?: number;
                confirm?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_tally_api_v1_export_tally_get: {
        parameters: {
            query?: {
                client_id?: number | null;
                approved_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_duplicates_api_v1_invoices__invoice_id__duplicates_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateScanResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_flags_api_v1_duplicates_flags_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateFlagOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_flag_api_v1_duplicates_flags__flag_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flag_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateResolve"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateFlagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reminder_preview_api_v1_reminders_preview_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_client_reminder_api_v1_clients__client_id__send_reminder_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderSend"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailReminderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reminder_history_api_v1_reminders_history_get: {
        parameters: {
            query?: {
                client_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailReminderOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_reminder_api_v1_reminders__reminder_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminder_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_reminders_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderTemplate"][];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
